# -*- coding: utf-8 -*-
"""Automatización de Exel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vgJSPcsFSqkgem7_KNKXZj1MeFJm7P-
"""

import pandas as pd
import numpy as np

alumnos = ["Juan Pérez", "María García", "Luis Rodríguez", "Ana Martínez", "Carlos López",
           "Elena Gómez", "Diego Díaz", "Sofía Hernández", "Jorge Ruiz", "Lucía Sanz"]
materias = ["Matemáticas", "Español", "Ciencias", "Historia", "Inglés"]

data = {materias[i]: np.random.randint(5, 11, size=10) for i in range(len(materias))}
data['Alumno'] = alumnos
data['Padre_Familia'] = [f"Padre/Tutor de {a}" for a in alumnos]

df = pd.DataFrame(data)

columnas = ['Alumno', 'Padre_Familia'] + materias
df = df[columnas]

df.to_excel("calificaciones.xlsx", index=False)
print("Archivo 'calificaciones.xlsx' generado con éxito.")

import pandas as pd
import numpy as np
from docx import Document

# 1. Datos de ejemplo
alumnos = ["Juan Pérez", "María García", "Luis Rodríguez", "Ana Martínez", "Carlos López",
           "Elena Gómez", "Diego Díaz", "Sofía Hernández", "Jorge Ruiz", "Lucía Sanz"]
materias = ["Matemáticas", "Español", "Ciencias", "Historia", "Inglés"]

data = {materias[i]: np.random.randint(5, 11, size=10) for i in range(len(materias))}
data['Alumno'] = alumnos
data['Padre_Familia'] = [f"Padre/Tutor de {a}" for a in alumnos]

df = pd.DataFrame(data)

def generar_cartas_con_recomendacion(dataframe):
    for _, row in dataframe.iterrows():
        doc = Document("carta formal.docx")

        # Reemplazos básicos [cite: 5, 6]
        reemplazos = {
            "Dirigido a. –": f"Dirigido a. – {row['Padre_Familia']}",
            "[Nombre del alumno/a]": row['Alumno'],
            "Sofía Hernández": row['Alumno'],
            "[Nombre de la materia]": "Todas las asignaturas"
        }

        for p in doc.paragraphs:
            for clave, valor in reemplazos.items():
                if clave in p.text:
                    p.text = p.text.replace(clave, str(valor))

        # Llenado de la Tabla
        if doc.tables:
            tabla = doc.tables[0]
            fila_datos = tabla.rows[1].cells
            fila_datos[0].text = str(row['Alumno'])
            for i, materia in enumerate(materias):
                fila_datos[i+1].text = str(row[materia])

        # --- LÓGICA DE RECOMENDACIÓN ---
        # Verificamos si hay alguna calificación <= 5
        reprobadas = [m for m in materias if row[m] <= 5]

        if reprobadas:
            # Insertar recomendación antes de la despedida
            materias_str = ", ".join(reprobadas)
            p_rec = doc.add_paragraph()
            run = p_rec.add_run(f"NOTA DE SEGUIMIENTO: Se ha observado un desempeño insuficiente en: {materias_str}. ")
            run.bold = True
            p_rec.add_run("Se recomienda reforzar estos temas en casa y programar una asesoría técnica para evitar el rezago académico.")

        # Guardar [cite: 1]
        nombre_archivo = f"Carta_{row['Alumno'].replace(' ', '_')}.docx"
        doc.save(nombre_archivo)
        print(f"Generada: {nombre_archivo} {'(Con recomendación)' if reprobadas else ''}")

generar_cartas_con_recomendacion(df)

