# -*- coding: utf-8 -*-
"""calificaciones v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpVBI_TPBc84zUR9hSn15jN30_LwNkBZ
"""

class AnalisisCalificaciones:
    def __init__(self):
        self.nombres = []
        self.calificaciones = []
        self.promedio_grupal = 0
        self.alumnos_excelentes = []

    def leer_datos(self):
        print("Introduce los nombres y calificaciones de 10 alumnos:")
        for i in range(10):
            nombre = input(f"Nombre del alumno {i+1}: ")
            calificacion = float(input(f"Calificación de {nombre}: "))
            self.nombres.append(nombre)
            self.calificaciones.append(calificacion)

    def realizar_proceso(self):
        self.promedio_grupal = sum(self.calificaciones) / len(self.calificaciones)

        for i in range(len(self.calificaciones)):
            if self.calificaciones[i] > 9.5:
                self.alumnos_excelentes.append((self.nombres[i], self.calificaciones[i]))

    def imprimir_resultados(self):
        print("\n--- Resultados ---")
        print(f"Promedio grupal de calificación: {self.promedio_grupal:.2f}")

        if self.alumnos_excelentes:
            print("\nAlumnos con calificación mayor a 9.5:")
            for nombre, calificacion in self.alumnos_excelentes:
                print(f"- {nombre}: {calificacion}")
        else:
            print("\nNo hay alumnos con calificación mayor a 9.5.")

analisis = AnalisisCalificaciones()

analisis.leer_datos()
analisis.realizar_proceso()
analisis.imprimir_resultados()