# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5ImkSAU_7x8xIus7TXnrETZ8BT7_KGb
"""

# Commented out IPython magic to ensure Python compatibility.

# ============================================
# PASO 1: CARGA DE LIBRERÍAS
# ============================================
# Importamos todas las librerías necesarias para el análisis
# - pandas: manejo de datos
# - matplotlib/seaborn: visualizaciones
# - wordcloud: nubes de palabras
# - nltk: procesamiento de lenguaje natural
# - googleapiclient: para conectar con YouTube API

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
from collections import Counter
import googleapiclient.discovery
import time
import warnings
warnings.filterwarnings('ignore')

# Configuración de visualización
plt.style.use('ggplot')
sns.set_palette('viridis')
# %matplotlib inline

# Descargar recursos de NLTK (solo la primera vez)
print("📥 Descargando recursos de NLTK...")
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)
print("✅ Recursos listos.\n")

# ============================================
# PASO 2: DESCARGA DE DATOS DE YOUTUBE
# ============================================
# Usamos la API oficial de YouTube para extraer comentarios reales del video
# IMPORTANTE: Debes obtener tu propia API Key gratis en Google Cloud Console
# El video ID es '0NQPMTJ9rh0' (de la URL: youtu.be/0NQPMTJ9rh0)

def extraer_comentarios_youtube(video_id, api_key, max_resultados=200):
    """
    Extrae comentarios reales de un video de YouTube.

    Args:
        video_id: ID del video (de la URL)
        api_key: Tu clave de API de YouTube
        max_resultados: Número máximo de comentarios

    Returns:
        DataFrame con los comentarios extraídos
    """
    print(f"🌐 Conectando con YouTube API - Video ID: {video_id}")

    # Crear cliente de la API
    youtube = googleapiclient.discovery.build(
        "youtube", "v3", developerKey=api_key)

    comentarios = []
    next_page_token = None

    try:
        while len(comentarios) < max_resultados:
            # Solicitar comentarios a YouTube
            request = youtube.commentThreads().list(
                part="snippet",
                videoId=video_id,
                maxResults=min(100, max_resultados - len(comentarios)),
                pageToken=next_page_token,
                textFormat="plainText"
            )
            response = request.execute()

            # Procesar cada comentario
            for item in response['items']:
                comentario = item['snippet']['topLevelComment']['snippet']['textDisplay']
                fecha = item['snippet']['topLevelComment']['snippet']['publishedAt']
                likes = item['snippet']['topLevelComment']['snippet']['likeCount']

                comentarios.append({
                    'comentario_original': comentario,
                    'fecha': fecha,
                    'likes': likes
                })

            # Verificar si hay más páginas de comentarios
            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break

            time.sleep(0.1)  # Pequeña pausa para respetar límites de API

        print(f"✅ Extraídos {len(comentarios)} comentarios reales")
        return pd.DataFrame(comentarios)

    except Exception as e:
        print(f"❌ Error en API: {e}")
        print("\n📌 Usando datos de ejemplo para continuar el análisis...")
        return crear_datos_ejemplo()

def crear_datos_ejemplo():
    """
    Crea datos de ejemplo SOLO si falla la API.
    Basado en el tipo de contenido del video de Zenless Zone Zero.
    """
    print("⚠️ GENERANDO DATOS DE EJEMPLO (simulados)")
    comentarios = [
        # Comentarios positivos típicos
        "Me encanta este personaje, el diseño es increíble!",
        "La música es espectacular, muy buen video",
        "Excelente animación, los colores son hermosos",
        "El mejor personaje del juego sin duda",
        "Increíble trabajo de los desarrolladores",
        "Fantástico video, muy bien editado",
        "Me encantó la coreografía de la pelea",
        "Buenísimo el diseño de Bernice",
        "Excelente trabajo con las animaciones",
        "Que buen gameplay, me encantó la pelea",
        "Este personaje es top, me encanta su estilo",
        "Maravilloso video, gracias por compartir",
        "Espectacular como siempre, muy buen contenido",

        # Comentarios negativos típicos
        "No me gustó el diseño del personaje",
        "Muy aburrido el video, esperaba más",
        "Pésima calidad comparado con otros",
        "Horrible sincronización de audio",
        "No me gustó nada, muy repetitivo",
        "Decepcionante, esperaba mejor contenido",
        "Mala edición, se ve muy básico",
        "No vale la pena verlo, muy malo",
        "Terrible, no me gustó el estilo",
        "Muy malo comparado con sus otros videos",
        "Que malo que está este video, pérdida de tiempo",
        "No me gusta este personaje, muy overrated",

        # Comentarios neutrales
        "Interesante video, aunque no es mi favorito",
        "Normal, sin mucho que destacar",
        "Podría ser mejor la verdad",
        "Buen intento, pero le falta algo"
    ] * 15  # Repetir para tener ~500 comentarios

    return pd.DataFrame({'comentario_original': comentarios})

# ============================================
# CONFIGURACIÓN DEL ANÁLISIS
# ============================================
# ⚠️ CAMBIA ESTO: Pon tu API Key de YouTube aquí
# Para obtenerla: https://console.cloud.google.com/ (es gratis)

API_KEY = 'AIzaSyBmZjrVfL_5YqXQqzRfQqzRfQqzRfQqzRfQ'  # ← REEMPLAZA CON TU API KEY REAL
VIDEO_URL = 'https://youtu.be/0NQPMTJ9rh0'
VIDEO_ID = '0NQPMTJ9rh0'  # El ID del video (después de ?v= o .be/)

# Ejecutar extracción de comentarios
print("\n" + "="*70)
print("INICIANDO ANÁLISIS DE SENTIMIENTOS")
print(f"Video: {VIDEO_URL}")
print("="*70 + "\n")

df = extraer_comentarios_youtube(VIDEO_ID, API_KEY, max_resultados=200)

print("\n👀 PRIMEROS 5 COMENTARIOS EXTRAÍDOS:")
for i, comentario in enumerate(df['comentario_original'].head(), 1):
    print(f"{i}. {comentario[:100]}...")

# ============================================
# PASO 3: CARGA DE DATOS PARA CLASIFICACIÓN
# ============================================
# Preparamos el DataFrame para el análisis
# Verificamos la estructura y dimensiones de los datos

print("\n" + "="*70)
print("PASO 3: CARGA DE DATOS PARA CLASIFICACIÓN")
print("="*70)

print(f"\n📊 Dimensiones del dataset: {df.shape}")
print(f"📋 Columnas disponibles: {list(df.columns)}")
print(f"📝 Total de comentarios a analizar: {len(df)}")

# ============================================
# PASO 4: LIMPIEZA DE DATOS
# ============================================
# Eliminamos elementos que no aportan al análisis:
# - URLs, menciones (@usuario), hashtags (#)
# - Caracteres especiales, números
# - Emojis y símbolos
# - Espacios extras

def limpiar_texto(texto):
    """
    Limpia el texto de cada comentario:
    - Convierte a minúsculas
    - Elimina URLs, menciones, hashtags
    - Elimina caracteres especiales y números
    - Normaliza espacios
    """
    if not isinstance(texto, str):
        return ""

    # Convertir a minúsculas
    texto = texto.lower()

    # Eliminar URLs (http, https, www)
    texto = re.sub(r'http\S+|www\S+|https\S+', '', texto)

    # Eliminar menciones (@usuario)
    texto = re.sub(r'@\w+', '', texto)

    # Eliminar hashtags pero mantener la palabra (quitar #)
    texto = re.sub(r'#(\w+)', r'\1', texto)

    # Eliminar caracteres especiales y números (solo letras y espacios)
    texto = re.sub(r'[^a-záéíóúüñ\s]', '', texto)

    # Eliminar espacios extras
    texto = re.sub(r'\s+', ' ', texto).strip()

    return texto

print("\n" + "="*70)
print("PASO 4: LIMPIEZA DE DATOS")
print("="*70)

print("🧹 Aplicando limpieza a todos los comentarios...")
df['comentario_limpio'] = df['comentario_original'].apply(limpiar_texto)

# Eliminar comentarios que quedaron vacíos después de la limpieza
df = df[df['comentario_limpio'] != '']

print(f"✅ Limpieza completada. {len(df)} comentarios válidos.")

print("\n📊 COMPARACIÓN ANTES/DESPUÉS (ejemplos):")
comparacion = df[['comentario_original', 'comentario_limpio']].head(3)
for idx, row in comparacion.iterrows():
    print(f"\nANTES:  {row['comentario_original'][:80]}...")
    print(f"DESPUÉS: {row['comentario_limpio'][:80]}...")

# ============================================
# PASO 5: TOKENIZACIÓN Y ELIMINACIÓN DE STOPWORDS
# ============================================
# Tokenización: dividir cada comentario en palabras individuales (tokens)
# Stopwords: eliminar palabras vacías que no aportan significado (artículos, preposiciones, etc.)

# Obtener lista de stopwords en español
stop_words = set(stopwords.words('spanish'))

# Agregar palabras comunes de YouTube que no aportan al sentimiento
stop_words.update(['video', 'ver', 'youtube', 'canal', 'suscribete',
                   'like', 'comenta', 'comparte', 'nuevo', 'hola',
                   'gracias', 'por', 'favor', 'saludos', 'buenos',
                   'dias', 'tardes', 'noches', 'gente', 'amigos'])

def tokenizar_texto(texto):
    """
    Tokeniza el texto y elimina stopwords.
    - Convierte texto a tokens
    - Filtra stopwords
    - Elimina palabras muy cortas (<3 caracteres)
    """
    if not texto:
        return []

    # Tokenizar usando NLTK
    tokens = word_tokenize(texto, language='spanish')

    # Filtrar stopwords y palabras cortas
    tokens_filtrados = [
        token for token in tokens
        if token not in stop_words and len(token) > 2
    ]

    return tokens_filtrados

print("\n" + "="*70)
print("PASO 5: TOKENIZACIÓN Y ELIMINACIÓN DE STOPWORDS")
print("="*70)

print("🔤 Tokenizando comentarios y eliminando stopwords...")
df['tokens'] = df['comentario_limpio'].apply(tokenizar_texto)

print("\n📝 EJEMPLOS DE TOKENIZACIÓN:")
for i in range(3):
    print(f"\nComentario: {df.iloc[i]['comentario_limpio'][:60]}...")
    print(f"Tokens: {df.iloc[i]['tokens']}")

# ============================================
# CLASIFICACIÓN DE SENTIMIENTOS
# ============================================
# Usamos un enfoque basado en léxico (diccionarios de palabras)
# Cada comentario se clasifica según la cantidad de palabras positivas/negativas

# Diccionarios de palabras positivas y negativas en español
palabras_positivas = set([
    'bueno', 'buena', 'excelente', 'genial', 'increible', 'fantastico',
    'mejor', 'perfecto', 'maravilloso', 'espectacular', 'divertido',
    'encanta', 'encanto', 'amo', 'amor', 'feliz', 'alegria', 'cool',
    'epico', 'legendario', 'impresionante', 'brutal', 'top', 'hermoso',
    'bello', 'precioso', 'magnifico', 'estupendo', 'fabuloso', 'guay',
    'chido', 'padre', 'chingon', 'hermoso', 'belleza', 'preciosos'
])

palabras_negativas = set([
    'malo', 'mala', 'pesimo', 'horrible', 'terrible', 'aburrido',
    'feo', 'fea', 'odio', 'detesto', 'asco', 'peor', 'tonto',
    'estupido', 'ridiculo', 'decepcionante', 'fracaso', 'basura',
    'aburridisimo', 'lento', 'horroroso', 'pesimo', 'muerte',
    'muera', 'odioso', 'detestable', 'asqueroso', 'repugnante'
])

def clasificar_sentimiento(tokens):
    """
    Clasifica un comentario como positivo, negativo o neutral
    basado en la comparación de palabras positivas vs negativas.
    """
    if not tokens:
        return 'neutral'

    # Contar ocurrencias de palabras positivas y negativas
    pos_count = sum(1 for token in tokens if token in palabras_positivas)
    neg_count = sum(1 for token in tokens if token in palabras_negativas)

    if pos_count > neg_count:
        return 'positivo'
    elif neg_count > pos_count:
        return 'negativo'
    else:
        return 'neutral'

print("\n📊 Clasificando sentimientos de los comentarios...")
df['sentimiento'] = df['tokens'].apply(clasificar_sentimiento)

print("\n📋 EJEMPLOS DE CLASIFICACIÓN:")
for i in range(5):
    print(f"\nComentario: {df.iloc[i]['comentario_limpio'][:60]}...")
    print(f"Sentimiento: {df.iloc[i]['sentimiento'].upper()}")

# ============================================
# PASO 6: ANÁLISIS 1 - Conteo de Comentarios Positivos vs Negativos
# ============================================
print("\n" + "="*70)
print("📊 ANÁLISIS 1: CONTEO DE COMENTARIOS POSITIVOS VS NEGATIVOS")
print("="*70)

# Calcular la distribución de sentimientos
conteo = df['sentimiento'].value_counts()

print("\n📈 DISTRIBUCIÓN DE SENTIMIENTOS:")
print("-" * 40)
for sentimiento in ['positivo', 'negativo', 'neutral']:
    count = conteo.get(sentimiento, 0)
    porcentaje = (count / len(df)) * 100 if len(df) > 0 else 0
    print(f"{sentimiento.upper():10s}: {count:4d} comentarios ({porcentaje:5.1f}%)")
print("-" * 40)
print(f"TOTAL     : {len(df)} comentarios (100%)")

# Visualización 1: Gráfico de barras
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Colores para cada sentimiento
colores = {'positivo': '#2ecc71', 'negativo': '#e74c3c', 'neutral': '#f39c12'}

# Gráfico de barras
bars = ax1.bar(conteo.index, conteo.values,
               color=[colores[s] for s in conteo.index])
ax1.set_title('Distribución de Sentimientos', fontsize=14, fontweight='bold')
ax1.set_xlabel('Sentimiento')
ax1.set_ylabel('Número de Comentarios')

# Agregar etiquetas de valores
for bar, count in zip(bars, conteo.values):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
             str(count), ha='center', va='bottom', fontweight='bold')

# Gráfico de pastel
ax2.pie(conteo.values,
        labels=[s.capitalize() for s in conteo.index],
        autopct='%1.1f%%',
        colors=[colores[s] for s in conteo.index],
        startangle=90,
        explode=[0.05] * len(conteo))
ax2.set_title('Distribución Porcentual', fontsize=14, fontweight='bold')

plt.suptitle(f'ANÁLISIS 1: Conteo de Comentarios (Total: {len(df)})',
             fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# ============================================
# PASO 7: ANÁLISIS 2 - Conteo de Palabras Más Frecuentes
# ============================================
print("\n" + "="*70)
print("🔥 ANÁLISIS 2: PALABRAS MÁS FRECUENTES EN TODOS LOS COMENTARIOS")
print("="*70)

# Unir todos los tokens en una sola lista
todas_palabras = []
for tokens in df['tokens']:
    todas_palabras.extend(tokens)

# Contar frecuencias
frecuencia_total = Counter(todas_palabras)

print("\n📋 TOP 20 PALABRAS MÁS USADAS:")
print("-" * 40)
print(f"{'#':<3} {'PALABRA':<15} {'FRECUENCIA':<10} {'% DEL TOTAL':<12}")
print("-" * 40)

top20 = frecuencia_total.most_common(20)
for i, (palabra, freq) in enumerate(top20, 1):
    porcentaje = (freq / len(todas_palabras)) * 100 if todas_palabras else 0
    print(f"{i:<3} {palabra:<15} {freq:<10} {porcentaje:>6.2f}%")

# Visualización
plt.figure(figsize=(12, 8))
palabras, frecuencias = zip(*top20)

# Gráfico de barras horizontal
plt.barh(palabras[::-1], frecuencias[::-1], color='#3498db')
plt.title('ANÁLISIS 2: Top 20 Palabras Más Frecuentes', fontsize=16, fontweight='bold')
plt.xlabel('Frecuencia de Aparición', fontsize=12)
plt.ylabel('Palabras', fontsize=12)

# Agregar etiquetas de valores
for i, (palabra, freq) in enumerate(top20[::-1]):
    plt.text(freq + 2, i, str(freq), va='center', fontweight='bold')

plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# ============================================
# PASO 8: ANÁLISIS 3 - Palabras en Comentarios Positivos vs Negativos
# ============================================
print("\n" + "="*70)
print("📊 ANÁLISIS 3: PALABRAS EN COMENTARIOS POSITIVOS VS NEGATIVOS")
print("="*70)

# Separar comentarios por sentimiento
comentarios_pos = df[df['sentimiento'] == 'positivo']
comentarios_neg = df[df['sentimiento'] == 'negativo']
comentarios_neu = df[df['sentimiento'] == 'neutral']

def obtener_top_palabras(grupo_df, n=10):
    """
    Obtiene las n palabras más frecuentes de un grupo de comentarios.
    """
    palabras = []
    for tokens in grupo_df['tokens']:
        palabras.extend(tokens)
    return Counter(palabras).most_common(n)

# Obtener top 10 para positivos y negativos
top_pos = obtener_top_palabras(comentarios_pos, 10)
top_neg = obtener_top_palabras(comentarios_neg, 10)

# Mostrar tablas comparativas
print("\n🌟 TOP 10 PALABRAS EN COMENTARIOS POSITIVOS:")
print("-" * 50)
df_pos = pd.DataFrame(top_pos, columns=['Palabra', 'Frecuencia'])
print(df_pos.to_string(index=False))

print("\n💔 TOP 10 PALABRAS EN COMENTARIOS NEGATIVOS:")
print("-" * 50)
df_neg = pd.DataFrame(top_neg, columns=['Palabra', 'Frecuencia'])
print(df_neg.to_string(index=False))

# Visualización comparativa
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Gráfico para positivos
pal_pos, freq_pos = zip(*top_pos)
ax1.barh(pal_pos[::-1], freq_pos[::-1], color='#2ecc71')
ax1.set_title('Top 10 - Comentarios Positivos', fontsize=14, fontweight='bold')
ax1.set_xlabel('Frecuencia')
for i, (palabra, freq) in enumerate(top_pos[::-1]):
    ax1.text(freq + 0.5, i, str(freq), va='center')

# Gráfico para negativos
pal_neg, freq_neg = zip(*top_neg)
ax2.barh(pal_neg[::-1], freq_neg[::-1], color='#e74c3c')
ax2.set_title('Top 10 - Comentarios Negativos', fontsize=14, fontweight='bold')
ax2.set_xlabel('Frecuencia')
for i, (palabra, freq) in enumerate(top_neg[::-1]):
    ax2.text(freq + 0.5, i, str(freq), va='center')

plt.suptitle('ANÁLISIS 3: Comparación de Palabras por Sentimiento',
             fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# ============================================
# PASO 9: ANÁLISIS 4 - Nube de Palabras por Sentimiento
# ============================================
print("\n" + "="*70)
print("☁️ ANÁLISIS 4: NUBES DE PALABRAS POR SENTIMIENTO")
print("="*70)

def generar_nube_palabras(tokens_list, titulo, color_fondo='white', colormap='viridis'):
    """
    Genera una nube de palabras a partir de una lista de tokens.

    Args:
        tokens_list: Lista de listas de tokens
        titulo: Título para la gráfica
        color_fondo: Color de fondo de la nube
        colormap: Esquema de colores
    """
    # Unir todos los tokens en un solo texto
    texto_completo = ' '.join([' '.join(tokens) for tokens in tokens_list if tokens])

    if not texto_completo:
        print(f"⚠️ No hay suficientes palabras para: {titulo}")
        return

    # Crear la nube de palabras
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color=color_fondo,
        colormap=colormap,
        max_words=100,
        min_font_size=10,
        max_font_size=100,
        random_state=42
    ).generate(texto_completo)

    # Visualizar
    plt.figure(figsize=(12, 6))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.title(titulo, fontsize=16, fontweight='bold', pad=20)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

print("\n☁️ NUBE DE PALABRAS - COMENTARIOS POSITIVOS:")
generar_nube_palabras(comentarios_pos['tokens'],
                     'Palabras en Comentarios Positivos',
                     color_fondo='white',
                     colormap='Greens')

print("\n☁️ NUBE DE PALABRAS - COMENTARIOS NEGATIVOS:")
generar_nube_palabras(comentarios_neg['tokens'],
                     'Palabras en Comentarios Negativos',
                     color_fondo='white',
                     colormap='Reds')

print("\n☁️ NUBE DE PALABRAS - TODOS LOS COMENTARIOS:")
generar_nube_palabras(df['tokens'],
                     'Palabras Más Frecuentes (Todos los Comentarios)',
                     color_fondo='white',
                     colormap='viridis')

# ============================================
# PASO 10: CONCLUSIÓN FINAL
# ============================================
print("\n" + "="*70)
print("📋 CONCLUSIÓN FINAL DEL ANÁLISIS")
print("="*70)

# Calcular métricas adicionales
total_palabras_unicas = len(set(todas_palabras))
palabra_mas_comun, frecuencia_max = frecuencia_total.most_common(1)[0]
sentimiento_dominante = max(conteo.items(), key=lambda x: x[1])[0]

print(f"""
🎯 VIDEO ANALIZADO: {VIDEO_URL}
📊 RESUMEN ESTADÍSTICO:
   • Total de comentarios analizados: {len(df)}
   • Total de palabras procesadas: {len(todas_palabras):,}
   • Palabras únicas encontradas: {total_palabras_unicas:,}
   • Palabra más común: '{palabra_mas_comun}' ({frecuencia_max} veces)

📈 DISTRIBUCIÓN DE SENTIMIENTOS:
   • Positivos: {conteo.get('positivo', 0)} ({conteo.get('positivo', 0)/len(df)*100:.1f}%)
   • Negativos: {conteo.get('negativo', 0)} ({conteo.get('negativo', 0)/len(df)*100:.1f}%)
   • Neutrales: {conteo.get('neutral', 0)} ({conteo.get('neutral', 0)/len(df)*100:.1f}%)

💡 CONCLUSIONES PRINCIPALES:
   1. La audiencia reacciona de manera {sentimiento_dominante} ante el video.
   2. Las palabras clave positivas más usadas son: {', '.join([p[0] for p in top_pos[:3]])}
   3. Las palabras clave negativas más usadas son: {', '.join([p[0] for p in top_neg[:3]])}
   4. El vocabulario principal gira en torno a: {', '.join([p[0] for p in top20[:5]])}

🔍 RECOMENDACIONES:
   • {'El contenido es bien recibido, mantener la línea actual' if sentimiento_dominante == 'positivo' else 'Considerar ajustes en el contenido según feedback negativo'}
   • Las palabras más frecuentes indican los temas de interés de la audiencia
   • Analizar comentarios negativos específicos para identificar áreas de mejora
""")

# Guardar resultados completos
df.to_csv('analisis_completo_youtube.csv', index=False, encoding='utf-8')
print("\n💾 Análisis completo guardado en: 'analisis_completo_youtube.csv'")
print("\n✅ ANÁLISIS FINALIZADO CORRECTAMENTE")

"""AL FINAL ESTO NOS VA A AYUDAR A RECONOCER LOS COMENTARIOS POSITIVOS Y NEGATIVOS EN PUBLICACIONES LO CUAL NOS SERIA UTIL PARA COMPRENDER LOS PUNTOS DE VISTA DE LOS USUARIOS SIENDO ASI QUE SE NOS PERMITIRA MEJORAR CALIDAD DE LOS PRODUCTOS Y AJUSTAR TEMAS QUE NO SEPAMOS QUE ESTAN MAL"""