# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-WuHDrYSUl3eYUh-NYnsSpCROzz3Wj5
"""

alumno = {
    'nombre': "César Daniel",
    'peso': "87 kilos",
    'telefono': "3113932423",
    'domicilio': "andador benito juarez 13",
    'carrera': "ciencia de datos e inteligencia artificial"
}

print(alumno['nombre'])
print(alumno['peso'])
print(alumno['telefono'])
print(alumno['domicilio'])
print(alumno['carrera'])

print("\nIterating through the dictionary:")
for key, value in alumno.items():
    print(f"{key}: {value}")