# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QO8hMwzWseIiedAKo6dipXx5CRHh4rMm
"""

import sqlite3

conn = sqlite3.connect('lite.db')
cur = conn.cursor()

cur.execute("CREATE TABLE IF NOT EXISTS alumno(nombre TEXT, edad INTEGER, altura REAL, matricula INTEGER PRIMARY KEY)")

todos_alumnos = [
    ('cesar', 17, 1.72, 2316903745),
    ('valeria', 17, 1.73, 231690374),
    ('Gael', 17, 1.68, 231690903),
    ('jesus', 17, 1.65, 231690805),
]

cur.execute("SELECT COUNT(*) FROM alumno")
count = cur.fetchone()[0]

if count == 0:

    cur.executemany("INSERT INTO alumno VALUES(?,?,?,?)", todos_alumnos)
    conn.commit()
    print("Se insertaron 4 nuevos registros.")
else:
    print(f"La tabla ya tiene {count} registros. No se insertaron nuevos datos.")

print("Lista de Alumnos")
cur.execute("SELECT * FROM alumno")
alumnos = cur.fetchall()

for i in alumnos:
    print(i)

conn.close()