# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GvcCzO01bsstszSIlhUu2O3RVE6pzZ6

**regrecion lineal **

La regresión lineal es uno de los algoritmos fundamentales dentro del Machine Learning. Se utiliza para analizar y predecir el comportamiento de un dato basándose en la relación que tiene con otro.
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

datos_dict = {
    'Celsius': [-40, -10, 0, 8, 15, 22, 38],
    'Fahrenheit': [-40, 14, 32, 46.4, 59, 71.6, 100.4]
}
datos = pd.DataFrame(datos_dict)

print("Visualizando la relación de los datos...")
sns.scatterplot(x='Celsius', y='Fahrenheit', data=datos, hue='Celsius', palette='coolwarm')

X = datos['Celsius'].values
y = datos['Fahrenheit'].values

X_procesada = X.reshape(-1, 1)
y_procesada = y.reshape(-1, 1)

modelo = LinearRegression()

modelo.fit(X_procesada, y_procesada)
print("¡Modelo entrenado con éxito!")

score = modelo.score(X_procesada, y_procesada)
print(f"Puntuación del modelo (R^2): {score}")

celsius_a_predecir = 123
prediccion = modelo.predict([[celsius_a_predecir]])

print(f"\nResultado:")
print(f"{celsius_a_predecir} grados Celsius son {prediccion[0][0]} grados Fahrenheit.")import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

datos_dict = {
    'Celsius': [-40, -10, 0, 8, 15, 22, 38],
    'Fahrenheit': [-40, 14, 32, 46.4, 59, 71.6, 100.4]
}
datos = pd.DataFrame(datos_dict)

print("Visualizando la relación de los datos...")
sns.scatterplot(x='Celsius', y='Fahrenheit', data=datos, hue='Celsius', palette='coolwarm')

X = datos['Celsius'].values
y = datos['Fahrenheit'].values

X_procesada = X.reshape(-1, 1)
y_procesada = y.reshape(-1, 1)


modelo = LinearRegression()

modelo.fit(X_procesada, y_procesada)
print("¡Modelo entrenado con éxito!")

score = modelo.score(X_procesada, y_procesada)
print(f"Puntuación del modelo (R^2): {score}")

celsius_a_predecir = 123
prediccion = modelo.predict([[celsius_a_predecir]])

print(f"\nResultado:")
print(f"{celsius_a_predecir} grados Celsius son {prediccion[0][0]} grados Fahrenheit.")

"""La regresión lineal aplicada a los negocios sirve para optimizar presupuestos mediante la predicción de ventas basada en la inversión publicitaria. En este modelo, la característica o variable $X$ representa la cantidad de dinero invertida en anuncios, mientras que la etiqueta o variable $y$ corresponde al número de ventas o ingresos generados. El algoritmo trabaja para identificar la relación entre estas variables, determinando cuánto aumenta el volumen de ventas por cada peso adicional invertido en publicidad. Al ajustar una línea de tendencia a los datos históricos, la empresa obtiene un modelo capaz de predecir cuántas ventas podría alcanzar el próximo mes si decide aumentar o disminuir su presupuesto publicitario. Esta herramienta permite a las organizaciones pasar de las suposiciones a la toma de decisiones estratégicas basadas totalmente en datos, visualizando claramente cómo el esfuerzo económico en marketing impacta directamente en los resultados del negocio.

La regresión lineal en el sector inmobiliario es uno de los usos más clásicos en Machine Learning para predecir el precio de las viviendas. En este modelo, el funcionamiento se basa en definir la característica $X$ como los metros cuadrados de una casa y la etiqueta $y$ como su precio de venta final. La relación establecida indica que, de manera general, a mayor tamaño de construcción el precio tiende a subir de forma lineal, lo que permite trazar una línea de tendencia que representa el modelo. Al entrenar el algoritmo con un conjunto de datos de casas vendidas anteriormente, el sistema aprende a ajustar esa línea a la realidad del mercado. Una vez que el modelo está listo, es posible ingresar los metros cuadrados de una casa nueva que el sistema nunca ha visto para obtener un precio estimado de mercado basado en la trayectoria de la línea ajustada
"""