# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_RFowhLGqh5ARXoDELov_WWCDxF2XfN
"""

# spam_detector_es.py - Versión mejorada con dataset incorporado

import re
import nltk
import pandas as pd
import joblib
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import os

# Descargar recursos de nltk (si no están)
try:
    nltk.download('punkt', quiet=True)
    nltk.download('stopwords', quiet=True)
    nltk.download('punkt_tab', quiet=True)
except:
    print("Descargando recursos de NLTK...")
    nltk.download('punkt')
    nltk.download('stopwords')
    nltk.download('punkt_tab')

stop_words = list(stopwords.words('spanish'))

def limpiar_texto(texto):
    """Limpia y normaliza el texto para el procesamiento"""
    texto = texto.lower()
    texto = re.sub(r'http\S+|www\S+|https\S+', '', texto, flags=re.MULTILINE)
    texto = re.sub(r'@\w+', '', texto)
    texto = re.sub(r'[^a-záéíóúüñ\s]', '', texto)
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

def crear_dataset_ejemplo():
    """
    Crea un dataset de ejemplo en español con mensajes de spam y ham.
    Incluye una variedad de ejemplos típicos de ambos tipos.
    """
    datos = {
        'label': [
            'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham',
            'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham',
            'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham',
            'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham',
            'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham'
        ],
        'message': [
            # HAM (mensajes legítimos)
            "Hola, ¿cómo estás? Te espero esta noche en casa para cenar",
            "Recordatorio: reunión de trabajo mañana a las 10am en la sala principal",
            "¿Puedes comprar pan y leche de camino a casa? Gracias",
            "Feliz cumpleaños! Que tengas un día maravilloso lleno de alegría",
            "La reunión se pospuso para el viernes a las 3pm. Confirmar asistencia",
            "Te envío el documento que me pediste revisalo cuando puedas",
            "¿Quedamos para tomar un café este finde? Hace tiempo que no nos vemos",
            "Tu pedido ha sido enviado y llegará en los próximos días",
            "Recordatorio: cita con el médico mañana a las 9:30",
            "Gracias por tu compra. Tu factura está disponible en nuestra web",
            "¿Vienes a la fiesta de fin de año? Será el sábado en mi casa",
            "Te escribo para confirmar nuestra cena del viernes",
            "El informe está listo, te lo envío por correo",
            "Nos vemos en el cine a las 8, no llegues tarde",
            "¿Puedes llamarme cuando tengas un momento? Gracias",
            "Tu suscripción ha sido renovada automáticamente",
            "Felicitaciones por tu nuevo trabajo! Me alegro mucho",
            "¿Has visto la última película de Almodóvar?",
            "Te recomiendo este restaurante, la comida es excelente",
            "Quedamos el martes para revisar el proyecto",
            "Tu cuenta ha sido verificada correctamente",
            "Gracias por contactar con atención al cliente",
            "La clase de español es el lunes a las 7pm",
            "Te adjunto las fotos de las vacaciones",
            "Mañana es festivo, no hay clase",

            # SPAM (mensajes fraudulentos)
            "¡FELICIDADES! Has ganado un iPhone 15 GRATIS. Reclama tu premio en: http://gana-iphone.com/click",
            "URGENTE: Tu cuenta bancaria ha sido bloqueada. Verifica tus datos aquí: https://banco-seguridad.com",
            "Gana hasta 1000€ al día trabajando desde casa. Únete ahora: www.trabajo-facil.com",
            "Has sido seleccionado para un premio de 5000€. Envíanos tus datos para reclamarlo",
            "Promoción exclusiva: 50% de descuento en productos de belleza. Compra ahora",
            "Tu paquete está esperando. Confirma tu dirección para la entrega: http://paquete-falso.com",
            "Felicidades, eres nuestro ganador mensual. Reclama 10000€ ya!",
            "Oferta de trabajo: Gana dinero fácil sin experiencia. Inscríbete ahora",
            "Tu suscripción ha expirado. Renueva para seguir disfrutando de beneficios",
            "Inversión garantizada: Duplica tu dinero en una semana. Invierte ahora",
            "Mensaje del sorteo: Eres el afortunado número 1000000. Llama ya!",
            "Tu cuenta de Netflix será suspendida. Actualiza tu método de pago",
            "Has recibido una herencia de un familiar lejano. Contacta con nosotros",
            "Oferta especial: Viaje a Cancún por solo 199€. Reserva ya!",
            "Gana seguidores gratis en Instagram y TikTok. Entra aquí",
            "Préstamos rápidos sin papeleos. Aceptamos morosos",
            "Tu orden de compra #12345 ha sido procesada. Verifica aquí",
            "Eres candidato a un empleo con salario de 3000€ mensuales",
            "Farmacia online: Medicamentos sin receta al mejor precio",
            "Tu tarjeta de crédito ha sido clonada. Verifica urgentemente",
            "Gana dinero viendo videos. Registrate gratis: http://gana-facil.com",
            "Has sido añadido a un grupo de WhatsApp de apuestas deportivas",
            "Criptomonedas: Invierte ahora y multiplica tu dinero en 24h",
            "Tu cuenta de Amazon tiene un cargo no reconocido. Verifica aquí",
            "Oferta de empleo: Trabaja desde casa y gana 2000€ semanales"
        ]
    }

    df = pd.DataFrame(datos)
    return df

def cargar_datos():
    """
    Intenta cargar un dataset externo, si no existe usa el dataset de ejemplo.
    """
    ruta_archivo = 'spam_es.csv'

    if os.path.exists(ruta_archivo):
        print(f"Cargando dataset desde {ruta_archivo}...")
        try:
            df = pd.read_csv(ruta_archivo)
            print("Dataset cargado exitosamente.")
            return df
        except Exception as e:
            print(f"Error al cargar el archivo: {e}")
            print("Usando dataset de ejemplo en su lugar.")
            return crear_dataset_ejemplo()
    else:
        print(f"Archivo {ruta_archivo} no encontrado.")
        print("Usando dataset de ejemplo incorporado.")
        return crear_dataset_ejemplo()

def entrenar_modelo(df):
    """Entrena el modelo de clasificación de spam"""

    # Verificar y adaptar columnas si es necesario
    if 'label' not in df.columns or 'message' not in df.columns:
        print("Adaptando nombres de columnas...")
        posibles_label = [col for col in df.columns if any(x in col.lower() for x in ['label', 'categoria', 'clase', 'tipo'])]
        posibles_message = [col for col in df.columns if any(x in col.lower() for x in ['message', 'texto', 'mensaje', 'contenido'])]

        if posibles_label and posibles_message:
            df = df.rename(columns={posibles_label[0]: 'label', posibles_message[0]: 'message'})
            print(f"Columnas renombradas: {posibles_label[0]} -> label, {posibles_message[0]} -> message")
        else:
            raise ValueError("No se pudieron identificar las columnas necesarias. El dataset debe tener columnas para etiqueta y mensaje.")

    # Limpiar textos
    print("Limpiando textos...")
    df['clean_message'] = df['message'].apply(limpiar_texto)

    # Verificar distribución de clases
    print(f"Distribución de clases:\n{df['label'].value_counts()}")

    # Vectorización
    print("Vectorizando textos...")
    vectorizer = TfidfVectorizer(max_features=5000, stop_words=stop_words)
    X = vectorizer.fit_transform(df['clean_message']).toarray()

    # Convertir etiquetas a numéricas
    # Acepta tanto 'spam'/'ham' como 1/0
    if df['label'].dtype == 'object':
        y = df['label'].map({'ham': 0, 'spam': 1, 'legitimo': 0, 'normal': 0})
        # Para cualquier valor no mapeado, intentar convertir a numérico
        if y.isna().any():
            y = pd.to_numeric(df['label'], errors='coerce')
    else:
        y = df['label']

    # Dividir datos
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Entrenar modelo
    print("Entrenando modelo Naive Bayes...")
    modelo = MultinomialNB()
    modelo.fit(X_train, y_train)

    # Evaluar modelo
    y_pred = modelo.predict(X_test)
    print("\n" + "="*50)
    print("RESULTADOS DEL ENTRENAMIENTO:")
    print("="*50)
    print(f"Precisión: {accuracy_score(y_test, y_pred):.2%}")
    print("\nMatriz de confusión:")
    print(confusion_matrix(y_test, y_pred))
    print("\nReporte de clasificación:")
    target_names = ['ham', 'spam'] if 1 in y_test.values else ['legítimo', 'spam']
    print(classification_report(y_test, y_pred, target_names=target_names))

    # Guardar modelo
    joblib.dump(modelo, 'modelo_spam_es.pkl')
    joblib.dump(vectorizer, 'vectorizer_es.pkl')
    print("\nModelo guardado como 'modelo_spam_es.pkl'")
    print("Vectorizador guardado como 'vectorizer_es.pkl'")

    return modelo, vectorizer

def predecir(texto, modelo, vectorizer):
    """Predice si un mensaje es spam o ham"""
    texto_limpio = limpiar_texto(texto)
    X_new = vectorizer.transform([texto_limpio])
    pred = modelo.predict(X_new)[0]
    prob = modelo.predict_proba(X_new)[0]
    clase = 'spam' if pred == 1 else 'ham'
    confianza = prob[pred] * 100
    return clase, confianza

def probar_modelo(modelo, vectorizer):
    """Ejecuta pruebas de predicción con ejemplos variados"""
    print("\n" + "="*50)
    print("PRUEBAS DE PREDICCIÓN:")
    print("="*50)

    pruebas = [
        "Hola, ¿cómo estás? Te espero esta noche en casa para cenar",
        "¡FELICIDADES! Has ganado un iPhone 15 GRATIS. Reclama en http://premios.com",
        "Recordatorio: reunión de trabajo mañana a las 10am",
        "GANA DINERO FÁCIL!!! Trabaja desde casa y gana 5000€ semanales. Entra ya!",
        "¿Puedes comprar pan y leche de camino a casa?",
        "Tu cuenta bancaria ha sido suspendida. Verifica aquí: http://banco-seguro.com",
        "Mañana es festivo, no hay clase. ¡A descansar!",
        "Inversión garantizada: Multiplica tu dinero en 24 horas. Inversión mínima 100€",
        "Te envío el documento que me pediste para revisar",
        "ÚLTIMA OPORTUNIDAD: Descuentos del 90% en todos los productos"
    ]

    for i, msg in enumerate(pruebas, 1):
        clase, conf = predecir(msg, modelo, vectorizer)
        print(f"\n{i}. Mensaje: {msg[:50]}..." if len(msg) > 50 else f"\n{i}. Mensaje: {msg}")
        print(f"   -> {clase.upper()} (confianza: {conf:.2f}%)")

def modo_interactivo(modelo, vectorizer):
    """Modo interactivo para probar mensajes personalizados"""
    print("\n" + "="*50)
    print("MODO INTERACTIVO:")
    print("="*50)
    print("Escribe 'salir' para terminar")

    while True:
        print("\n" + "-"*30)
        mensaje = input("Introduce un mensaje para analizar: ")

        if mensaje.lower() in ['salir', 'exit', 'quit']:
            print("¡Hasta luego!")
            break

        if mensaje.strip():
            clase, conf = predecir(mensaje, modelo, vectorizer)
            print(f"\nRESULTADO: {clase.upper()}")
            print(f"Confianza: {conf:.2f}%")
        else:
            print("Por favor, introduce un mensaje válido.")

if __name__ == "__main__":
    print("="*50)
    print("DETECTOR DE SPAM EN ESPAÑOL")
    print("="*50)

    # Cargar o crear datos
    print("\n1. CARGANDO DATOS...")
    df = cargar_datos()

    # Entrenar modelo
    print("\n2. ENTRENANDO MODELO...")
    try:
        modelo, vectorizer = entrenar_modelo(df)

        # Probar modelo
        probar_modelo(modelo, vectorizer)

        # Modo interactivo
        modo_interactivo(modelo, vectorizer)

    except Exception as e:
        print(f"\nError durante el entrenamiento: {e}")
        print("Verifica que el dataset tenga el formato correcto.")