# -*- coding: utf-8 -*-
"""SQlite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ha4DnU9zu5H2EVhuTQxQAlVEZJqFMXxU
"""

# Programa para manejar datos de alumnos del CONALEP

# Cada alumno es un diccionario
# La "tabla" es una lista de alumnos
tabla_alumnos = [
    {"matricula": "25092008", "nombre": "César Daniel", "edad": 17, "carrera": "CDIA"},
    {"matricula": "10022008", "nombre": "Jesus López", "edad": 18, "carrera": "automotriz"},
    {"matricula": "01022008", "nombre": "valeria valerio", "edad": 17, "carrera": "Enfermería"}
]

def mostrar_tabla():
    print("\n--- DATOS DE LOS ALUMNOS ---")
    if not tabla_alumnos:
        print("No hay alumnos registrados.")
        return
    for alumno in tabla_alumnos:
        print(f"Matrícula: {alumno['matricula']}, Nombre: {alumno['nombre']}, Edad: {alumno['edad']}, Carrera: {alumno['carrera']}")
    print("------------------------------")

def modificar_alumno(matricula):
    for alumno in tabla_alumnos:
        if alumno["matricula"] == matricula:
            print(f"Modificando datos del alumno {alumno['nombre']}")
            alumno["nombre"] = input("Nuevo nombre: ") or alumno["nombre"]
            alumno["edad"] = int(input("Nueva edad: ") or alumno["edad"])
            alumno["carrera"] = input("Nueva carrera: ") or alumno["carrera"]
            print("Alumno modificado correctamente.\n")
            return
    print("No se encontró un alumno con esa matrícula.\n")

def borrar_alumno(matricula):
    for alumno in tabla_alumnos:
        if alumno["matricula"] == matricula:
            tabla_alumnos.remove(alumno)
            print(f"Alumno con matrícula {matricula} eliminado correctamente.\n")
            return
    print("No se encontró un alumno con esa matrícula.\n")

def menu():
    while True:
        print("\n========= MENÚ PRINCIPAL =========")
        print("1. Mostrar todos los alumnos")
        print("2. Modificar alumno")
        print("3. Borrar alumno")
        print("4. Salir")
        opcion = input("Selecciona una opción: ")

        if opcion == "1":
            mostrar_tabla()
        elif opcion == "2":
            matricula = input("Ingresa la matrícula del alumno a modificar: ")
            modificar_alumno(matricula)
        elif opcion == "3":
            matricula = input("Ingresa la matrícula del alumno a borrar: ")
            borrar_alumno(matricula)
        elif opcion == "4":
            print("Saliendo del programa...")
            break
        else:
            print("Opción no válida. Intenta nuevamente.")

menu()