# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16s3T2Lc6iqv86Ecc9CBNCKE4bdG8jH7Z
"""

temp= [80, 72, 95, 82, 79, 72, 85]
#(32 °F − 32) × 5/9 = 0 °C

ntemp= []
for i in temp:
  ntemp.append( (i - 32)* 5/9 )
print("la temperatura en centigrados es de")
print(ntemp)