# -*- coding: utf-8 -*-
"""TRIANGULO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjqw-s-UJ_gq6jocuzzsh9PCj-CyQVae
"""

class TRIANGULO():
  Base = 20
  altura = 15

  def area(self):
    calculated_area = (self.Base * self.altura) / 2
    print(f"El área del triangulo es: {calculated_area}")

  def mostrar_altura(self):
    print(f"{self.altura} es la medida de la altura del triangulo")

triangulo_instance = TRIANGULO()
triangulo_instance.area()
triangulo_instance.mostrar_altura()