# -*- coding: utf-8 -*-
"""TRIANGULO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjqw-s-UJ_gq6jocuzzsh9PCj-CyQVae
"""

class TRIANGULO():
  Base = 20
  altura = 15

  def area(self):
    print(f"{self.Base} es la medida de la base del triangulo")
  def altura(self):
    print(f"{self.altura} es la medida de la altura del triangulo")
area = TRIANGULO()
area.area()
area.altura()