# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSK3CI6msBNjcdRrEuu2zWea1qbCWBuS
"""

class estudiante():
  nombre = "Cesar Daniel Marquez Rivas"
  peso = 87
  edad = 16
  promedio = 5.8

  def inscripcion(self):
    print(f"{self.nombre} esta inscrito")
  def asesorias(self):
    print("el alumno esta en asesorias")
alumno=estudiante()
alumno.inscripcion()
alumno.nombre = "Cesar Daniel Marquez Rivas"
alumno.asesorias()