# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CY7VNFpFNmp1tRtY72WXOXa27MdLkZ_e

importamos y leemos el archivo
"""

import pandas as pd

Datos = pd.read_csv('housing.csv')

"""hacemos esto para ver los primeros 5 datos y su demas informacion como la latitud, longitud, etc."""

Datos.head()

"""aqui revisamos todos lso datos que hay y todos los resultados que tiene de forma general"""

Datos["ocean_proximity"].value_counts()

"""aqui muestra los datos que tiene vacios y cuales vienen vacios ademas de su tipo"""

Datos.info()

"""aqui nos da algunos datos interesantes como el promedio, la cantidad de registros etc."""

Datos.describe()

"""creamos histogramas y ajustamos su tamaño"""

Datos.hist(figsize=(15,8))

"""aqui usamos el seaborn para crear mapas mas detallados y entender mejor la informacion"""

import seaborn as sb
sb.scatterplot(x="longitude", y="latitude", data=Datos, hue="median_house_value", size=Datos["population"]/100)

"""usamos el drop na para eliminar los datos inutiles que hay asi permitiendo visualizar mejor"""

Datos.info()

datos_na = Datos.dropna()

"""aqui tenemos que comvertir las caracteristicas categoricas en numericas"""

datos_na["ocean_proximity"]

datos_na["ocean_proximity"].value_counts()

#usamos dummies para crear columnas
dummies = pd.get_dummies(datos_na["ocean_proximity"])

datos_na = datos_na.join(dummies)
#aqui crea otro set de datos que agrega loq ue hicimos antes

datos_na.head()

#aqui el apartado oceanproximity ya no funciona asi que tenemos que eliminarlo
datos_na = datos_na.drop("ocean_proximity", axis=1)

datos_na.head()

#otra funcion importante son las correlaciones
datos_na.corr()

sb.set(rc={'figure.figsize':(11.7,8.27)})
sb.heatmap(datos_na.corr(), annot=True)

#aqui nos centramos en el dato que realmente nos interesa el cual es el precio de las casas
datos_na.corr()["median_house_value"].sort_values(ascending=False)

